"""empty message

Revision ID: eccd42e86d12
Revises: 24ae41693c74
Create Date: 2018-03-03 23:29:28.831303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eccd42e86d12'
down_revision = '24ae41693c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('cms_role', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_role', 'name')
    # ### end Alembic commands ###
