"""empty message

Revision ID: dabab225f5ea
Revises: 4f615835f1ae
Create Date: 2018-03-04 08:50:04.467667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabab225f5ea'
down_revision = '4f615835f1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_role_user',
    sa.Column('cms_role', sa.Integer(), nullable=False),
    sa.Column('cms_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cms_role'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['cms_user'], ['cms_user.id'], ),
    sa.PrimaryKeyConstraint('cms_role', 'cms_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_role_user')
    op.drop_table('cms_role')
    # ### end Alembic commands ###
